// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTable.DatabaseConnection;

#nullable disable

namespace TimeTable.Migrations
{
    [DbContext(typeof(TimeTableContext))]
    partial class TimeTableContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TimeTable.Modules.ClockTimes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("time");
                });

            modelBuilder.Entity("TimeTable.Modules.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnzLessons")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("education");
                });

            modelBuilder.Entity("TimeTable.Modules.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("person");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TimeTable.Modules.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("room");
                });

            modelBuilder.Entity("TimeTable.Modules.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("_description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_premises")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.HasIndex("TeacherId");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("TimeTable.Modules.Student", b =>
                {
                    b.HasBaseType("TimeTable.Modules.Person");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<int>("EducationSemester")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLessons")
                        .HasColumnType("int");

                    b.HasIndex("EducationId");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("TimeTable.Modules.Teacher", b =>
                {
                    b.HasBaseType("TimeTable.Modules.Person");

                    b.Property<int>("NumberOfWorkDays")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool>("Teached")
                        .HasColumnType("tinyint(1)");

                    b.HasIndex("StudentId");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("TimeTable.Modules.ClockTimes", b =>
                {
                    b.HasOne("TimeTable.Modules.Teacher", null)
                        .WithMany("UnavailableTimeSlots")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TimeTable.Modules.Subject", b =>
                {
                    b.HasOne("TimeTable.Modules.Education", null)
                        .WithMany("Subjects")
                        .HasForeignKey("EducationId");

                    b.HasOne("TimeTable.Modules.Teacher", null)
                        .WithMany("TeachedSubject")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TimeTable.Modules.Student", b =>
                {
                    b.HasOne("TimeTable.Modules.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTable.Modules.Person", "Person")
                        .WithOne()
                        .HasForeignKey("TimeTable.Modules.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TimeTable.Modules.Teacher", b =>
                {
                    b.HasOne("TimeTable.Modules.Person", "Person")
                        .WithOne()
                        .HasForeignKey("TimeTable.Modules.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTable.Modules.Student", null)
                        .WithMany("Teachers")
                        .HasForeignKey("StudentId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TimeTable.Modules.Education", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TimeTable.Modules.Student", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TimeTable.Modules.Teacher", b =>
                {
                    b.Navigation("TeachedSubject");

                    b.Navigation("UnavailableTimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
